language: dart
mono: none

dotnet: 3.1.100
services:
  - docker
branches:
  except:
    - master

jobs:
  include:
    - stage: build
      name: "Build Web App"
      script: 
        - cd minitwit_frontend && docker build -t minitwit:frontend-b -f Dockerfile.build .
        - docker run minitwit:frontend-b /bin/sh -c 'flutter build web'

    - stage: test
      name: "Run Tests"
      script: 
        - cd minitwit_frontend && docker build -t minitwit:frontend-b -f Dockerfile.build .
        - docker run minitwit:frontend-b /bin/sh -c 'flutter test'

    # Build docker image and push to dockerhub:
    - stage: deliver
      if: tag IS present
      name: Upload docker image
      env:
        - ORG_NAME=lazyopsdev
        - IMAGE_NAME=frontend
        - DEFAULT_DOCKER_TAG=latest
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd minitwit_frontend && docker build -t $IMAGE_NAME .
        - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
        - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"
        - docker push "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
        - docker push "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"

    # GitHub auto merge to master:
    - stage: auto-merge
      if: tag IS present
      name: Merge to master
      env:
        - GITHUB_USER_EMAIL="lazyopsdev@gmail.com"
        - GITHUB_USER_NAME="lazyopsdev-ci"
        - GITHUB_REPO_URI="LazyOpsDev/Minitwit.Frontend"
      script:
        - git config --global user.email "$GITHUB_USER_EMAIL"
        - git config --global user.name "$GITHUB_USER_NAME"
        - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
        - git fetch --all || exit
        - git checkout master || exit
        - git merge --no-ff "$TRAVIS_COMMIT" || exit
        - git remote add travis-origin https://${GITHUB_USER_NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO_URI}.git > /dev/null 2>&1
        - git push --quiet --set-upstream travis-origin master

notifications:
  email:
    - krza@itu.dk
    - phko@itu.dk
    - alsb@itu.dk
    - arca@itu.dk
